### ISSUE TITLE
search docs option in the web is not working

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/docs#30] opened 2015-10-29 09:50 UTC
open                  http://cloudslang-docs.readthedocs.org/en/v0.8/
and try to use the search  you'll get

"no result found . bummer."

**Comment by SamMarkowitz** [comment] 2015-10-29 12:17
duplicate of cloudslang/CloudSlang.github.io#137

**Closed as completed by SamMarkowitz** 2015-10-29 12:17 UTC
Labels: kind/bug
